name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate airports.yaml
        uses: thiagodnf/yaml-schema-checker@v0.0.12
        with:
          jsonSchemaFile: schemas/airports.schema.json
          yamlFiles: airports.yaml

      - name: Validate navaids.yaml
        uses: thiagodnf/yaml-schema-checker@v0.0.12
        with:
          jsonSchemaFile: schemas/navaids.schema.json
          yamlFiles: navaids.yaml

      - name: Create airports.json
        run: |
          yq airports.yaml > /dev/null
          yq -o=json -I=0 '[.[] | .ID = (.ID | tostring) | .Name = (.Name | tostring)]' airports.yaml > airports.json

      - name: Create navaids.json
        run: |
          yq navaids.yaml > /dev/null
          yq -o=json -I=0 '[.[] | .ID = (.ID | tostring) | .Name = (.Name | tostring)]' navaids.yaml > navaids.json
